openapi: 3.0.3
info:
  title: Customers API
  description: API for managing bank customers
  version: 1.0.0
tags:
  - name: customers
    description: Operations about customers
paths:
  /customers:
    get:
      tags:
        - customers
      operationId: getAllCustomers
      summary: Get all customers
      responses:
        '200':
          description: List of customers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      tags:
        - customers
      operationId: createCustomer
      summary: Create a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '201':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /customers/{id}:
    get:
      tags:
        - customers
      operationId: getCustomerById
      summary: Get customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Customer found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
    put:
      tags:
        - customers
      operationId: updateCustomer
      summary: Update an existing customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '200':
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
    delete:
      tags:
        - customers
      operationId: deleteCustomer
      summary: Delete a customer
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Customer deleted successfully
        '404':
          description: Customer not found
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        personalIdNumber:
          type: string
          description: Unique personal identification number
        phoneNumber:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
    CustomerRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - phoneNumber
        - personalIdNumber
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        personalIdNumber:
          type: string
          description: Unique personal identification number
        phoneNumber:
          type: string
